@php($editing = $service->exists)

<form method="POST" action="{{ $editing ? route('admin.services.update', $service) : route('admin.services.store') }}" enctype="multipart/form-data" class="mt-7 space-y-6">
    @csrf
    @if ($editing) @method('PUT') @endif
    @if ($errors->any())<div role="alert" class="rounded-sm border border-red-400/30 bg-red-400/10 p-4 text-sm text-red-200"><p class="font-medium">Revisa los campos marcados:</p><ul class="mt-2 list-inside list-disc space-y-1">@foreach ($errors->all() as $error)<li>{{ $error }}</li>@endforeach</ul></div>@endif
    <div class="grid gap-5 sm:grid-cols-2">
        <div><label for="name" class="mono-label mb-2 block text-white/65">Nombre *</label><input id="name" name="name" value="{{ old('name', $service->name) }}" required maxlength="160" class="w-full rounded-sm border border-white/10 bg-black/35 px-4 py-3 text-sm text-white outline-none focus:border-cyan focus:ring-2 focus:ring-cyan/15" aria-describedby="name-error">@error('name')<p id="name-error" class="mt-2 text-sm text-red-300">{{ $message }}</p>@enderror</div>
        <div><label for="slug" class="mono-label mb-2 block text-white/65">Slug <span class="text-white/35">(opcional, editable)</span></label><input id="slug" name="slug" value="{{ old('slug', $service->slug) }}" maxlength="180" pattern="[A-Za-z0-9_-]+" placeholder="se-genera-desde-el-nombre" class="w-full rounded-sm border border-white/10 bg-black/35 px-4 py-3 text-sm text-white outline-none focus:border-cyan focus:ring-2 focus:ring-cyan/15" aria-describedby="slug-help slug-error"><p id="slug-help" class="mt-2 text-xs text-white/45">Solo letras, números, guiones y guiones bajos.</p>@error('slug')<p id="slug-error" class="mt-2 text-sm text-red-300">{{ $message }}</p>@enderror</div>
        <div class="sm:col-span-2"><label for="short_description" class="mono-label mb-2 block text-white/65">Descripción corta *</label><textarea id="short_description" name="short_description" required maxlength="300" rows="2" class="w-full rounded-sm border border-white/10 bg-black/35 px-4 py-3 text-sm text-white outline-none focus:border-cyan focus:ring-2 focus:ring-cyan/15">{{ old('short_description', $service->short_description) }}</textarea>@error('short_description')<p class="mt-2 text-sm text-red-300">{{ $message }}</p>@enderror</div>
        <div class="sm:col-span-2"><label for="description" class="mono-label mb-2 block text-white/65">Descripción completa * <span class="text-white/35">(texto plano; HTML no permitido)</span></label><textarea id="description" name="description" required maxlength="20000" rows="8" class="w-full rounded-sm border border-white/10 bg-black/35 px-4 py-3 text-sm leading-6 text-white outline-none focus:border-cyan focus:ring-2 focus:ring-cyan/15">{{ old('description', $service->description) }}</textarea>@error('description')<p class="mt-2 text-sm text-red-300">{{ $message }}</p>@enderror</div>
        <div><label for="icon" class="mono-label mb-2 block text-white/65">Identificador del icono</label><input id="icon" name="icon" value="{{ old('icon', $service->icon) }}" maxlength="64" pattern="[A-Za-z0-9_-]+" placeholder="gamepad-2" class="w-full rounded-sm border border-white/10 bg-black/35 px-4 py-3 text-sm text-white outline-none focus:border-cyan focus:ring-2 focus:ring-cyan/15" aria-describedby="icon-help icon-error"><p id="icon-help" class="mt-2 text-xs text-white/45">Se muestra como etiqueta de texto; admite letras, números, - y _.</p>@error('icon')<p id="icon-error" class="mt-2 text-sm text-red-300">{{ $message }}</p>@enderror</div>
        <div><label for="image" class="mono-label mb-2 block text-white/65">Imagen <span class="text-white/35">(opcional)</span></label><input id="image" name="image" type="file" accept="image/jpeg,image/png,image/webp" class="block w-full rounded-sm border border-white/10 bg-black/35 p-3 text-sm text-white file:mr-4 file:rounded-sm file:border-0 file:bg-cyan file:px-3 file:py-2 file:font-mono file:text-xs file:font-semibold file:text-void" aria-describedby="image-help image-error"><p id="image-help" class="mt-2 text-xs text-white/45">JPG, PNG o WebP; máximo 5 MB y 6000 × 6000 px.</p>@error('image')<p id="image-error" class="mt-2 text-sm text-red-300">{{ $message }}</p>@enderror
            @if ($editing && $service->image)<img src="{{ \Illuminate\Support\Facades\Storage::disk('public')->url($service->image) }}" alt="" class="mt-3 h-24 w-36 rounded-sm border border-white/10 object-cover">@endif
        </div>
        <div><label for="button_text" class="mono-label mb-2 block text-white/65">Texto del botón</label><input id="button_text" name="button_text" value="{{ old('button_text', $service->button_text) }}" maxlength="100" class="w-full rounded-sm border border-white/10 bg-black/35 px-4 py-3 text-sm text-white outline-none focus:border-cyan focus:ring-2 focus:ring-cyan/15">@error('button_text')<p class="mt-2 text-sm text-red-300">{{ $message }}</p>@enderror</div>
        <div><label for="button_url" class="mono-label mb-2 block text-white/65">URL del botón</label><input id="button_url" name="button_url" type="url" value="{{ old('button_url', $service->button_url) }}" maxlength="2048" placeholder="https://…" class="w-full rounded-sm border border-white/10 bg-black/35 px-4 py-3 text-sm text-white outline-none focus:border-cyan focus:ring-2 focus:ring-cyan/15">@error('button_url')<p class="mt-2 text-sm text-red-300">{{ $message }}</p>@enderror</div>
        <div><label for="position" class="mono-label mb-2 block text-white/65">Orden</label><input id="position" name="position" type="number" min="0" max="65535" step="1" required value="{{ old('position', $service->position ?? 0) }}" class="w-full rounded-sm border border-white/10 bg-black/35 px-4 py-3 text-sm text-white outline-none focus:border-cyan focus:ring-2 focus:ring-cyan/15">@error('position')<p class="mt-2 text-sm text-red-300">{{ $message }}</p>@enderror</div>
        <div class="flex items-center gap-3 self-center"><input type="hidden" name="is_active" value="0"><input id="is_active" name="is_active" type="checkbox" value="1" @checked((bool) old('is_active', $service->is_active ?? false)) class="h-4 w-4 accent-cyan"><label for="is_active" class="text-sm text-white/75">Activo</label></div>
        <div><label for="seo_title" class="mono-label mb-2 block text-white/65">Título SEO</label><input id="seo_title" name="seo_title" value="{{ old('seo_title', $service->seo_title) }}" maxlength="180" class="w-full rounded-sm border border-white/10 bg-black/35 px-4 py-3 text-sm text-white outline-none focus:border-cyan focus:ring-2 focus:ring-cyan/15">@error('seo_title')<p class="mt-2 text-sm text-red-300">{{ $message }}</p>@enderror</div>
        <div><label for="meta_description" class="mono-label mb-2 block text-white/65">Meta descripción</label><input id="meta_description" name="meta_description" value="{{ old('meta_description', $service->meta_description) }}" maxlength="300" class="w-full rounded-sm border border-white/10 bg-black/35 px-4 py-3 text-sm text-white outline-none focus:border-cyan focus:ring-2 focus:ring-cyan/15">@error('meta_description')<p class="mt-2 text-sm text-red-300">{{ $message }}</p>@enderror</div>
    </div>
    <div class="flex flex-wrap gap-3 border-t border-white/10 pt-5"><button type="submit" class="focus-cyan rounded-sm bg-cyan px-5 py-3 font-mono text-xs font-semibold tracking-wider text-void transition hover:brightness-110">{{ $editing ? 'GUARDAR CAMBIOS' : 'CREAR SERVICIO' }}</button><a href="{{ route('admin.services.index') }}" class="focus-cyan rounded-sm border border-white/15 px-5 py-3 font-mono text-xs tracking-wider text-white/70 hover:border-white/30">CANCELAR</a></div>
</form>
