@extends('layouts.admin')

@section('title', 'Configuración general')
@section('breadcrumb', 'CONFIGURACIÓN / GENERAL')

@section('content')
<div class="mx-auto max-w-5xl space-y-6">
    <div><p class="mono-label text-cyan">// IDENTIDAD Y PRESENTACIÓN</p><h1 class="mt-2 font-display text-3xl font-semibold text-white">Configuración general</h1><p class="mt-2 max-w-3xl text-sm leading-6 text-white/55">Administra la información pública del sitio. Las credenciales y secretos de infraestructura no se guardan ni se exponen aquí.</p></div>
    @if (session('status'))<div role="status" class="rounded-sm border border-emerald-400/20 bg-emerald-400/5 p-4 text-sm text-emerald-200">{{ session('status') }}</div>@endif
    @if ($errors->any())<div role="alert" class="rounded-sm border border-rose-400/20 bg-rose-400/5 p-4 text-sm text-rose-200"><p class="font-medium">Revisa los campos indicados.</p><ul class="mt-2 list-inside list-disc">@foreach ($errors->all() as $error)<li>{{ $error }}</li>@endforeach</ul></div>@endif

    <form method="POST" action="{{ route('admin.settings.update') }}" enctype="multipart/form-data" class="space-y-6">
        @csrf @method('PUT')
        <section class="glass-panel space-y-5 rounded-md p-5 sm:p-7" aria-labelledby="identity-title">
            <div><h2 id="identity-title" class="font-display text-lg font-semibold text-white">Identidad</h2><p class="mt-1 text-sm text-white/45">El nombre del sitio también se usa como título global de SEO.</p></div>
            <div><label for="site_name" class="mb-2 block text-sm text-white/75">Nombre del sitio</label><input id="site_name" name="site_name" required maxlength="180" value="{{ old('site_name', $settings->site_name) }}" class="w-full rounded-sm border border-white/15 bg-black/25 px-3 py-3 text-white focus:border-cyan focus:outline-none">@error('site_name')<p class="mt-1 text-sm text-rose-300">{{ $message }}</p>@enderror</div>
            <div class="grid gap-6 md:grid-cols-2">
                <div><label for="logo" class="mb-2 block text-sm text-white/75">Logo (JPG, PNG o WebP; máximo 5 MB)</label>@if($settings->logo_path)<img src="{{ Storage::disk('public')->url($settings->logo_path) }}" alt="Logo actual del sitio" class="mb-3 h-14 max-w-56 object-contain">@endif<input id="logo" name="logo" type="file" accept="image/jpeg,image/png,image/webp" class="block w-full text-sm text-white/65 file:mr-3 file:rounded-sm file:border-0 file:bg-cyan file:px-3 file:py-2 file:font-semibold file:text-void">@error('logo')<p class="mt-1 text-sm text-rose-300">{{ $message }}</p>@enderror<input type="hidden" name="remove_logo" value="0"><label class="mt-3 flex items-center gap-2 text-xs text-white/55"><input type="checkbox" name="remove_logo" value="1" class="accent-cyan">Eliminar logo actual</label></div>
                <div><label for="favicon" class="mb-2 block text-sm text-white/75">Favicon (PNG, JPG o WebP; máximo 2 MB)</label>@if($settings->favicon_path)<img src="{{ Storage::disk('public')->url($settings->favicon_path) }}" alt="Favicon actual del sitio" class="mb-3 h-10 w-10 object-contain">@endif<input id="favicon" name="favicon" type="file" accept="image/jpeg,image/png,image/webp" class="block w-full text-sm text-white/65 file:mr-3 file:rounded-sm file:border-0 file:bg-cyan file:px-3 file:py-2 file:font-semibold file:text-void">@error('favicon')<p class="mt-1 text-sm text-rose-300">{{ $message }}</p>@enderror<input type="hidden" name="remove_favicon" value="0"><label class="mt-3 flex items-center gap-2 text-xs text-white/55"><input type="checkbox" name="remove_favicon" value="1" class="accent-cyan">Eliminar favicon actual</label></div>
            </div>
        </section>

        <section class="glass-panel space-y-5 rounded-md p-5 sm:p-7" aria-labelledby="contact-title">
            <div><h2 id="contact-title" class="font-display text-lg font-semibold text-white">Información de contacto</h2><p class="mt-1 text-sm text-white/45">Estos datos pueden aparecer en el pie de página público.</p></div>
            <div class="grid gap-5 sm:grid-cols-2"><div><label for="contact_email" class="mb-2 block text-sm text-white/75">Correo de contacto</label><input id="contact_email" name="contact_email" type="email" maxlength="254" value="{{ old('contact_email', $settings->contact_email) }}" class="w-full rounded-sm border border-white/15 bg-black/25 px-3 py-3 text-white">@error('contact_email')<p class="mt-1 text-sm text-rose-300">{{ $message }}</p>@enderror</div><div><label for="phone" class="mb-2 block text-sm text-white/75">Teléfono</label><input id="phone" name="phone" type="tel" maxlength="60" value="{{ old('phone', $settings->phone) }}" class="w-full rounded-sm border border-white/15 bg-black/25 px-3 py-3 text-white">@error('phone')<p class="mt-1 text-sm text-rose-300">{{ $message }}</p>@enderror</div></div>
            <div><label for="address" class="mb-2 block text-sm text-white/75">Dirección</label><input id="address" name="address" maxlength="500" value="{{ old('address', $settings->address) }}" class="w-full rounded-sm border border-white/15 bg-black/25 px-3 py-3 text-white">@error('address')<p class="mt-1 text-sm text-rose-300">{{ $message }}</p>@enderror</div>
            <div><label for="description" class="mb-2 block text-sm text-white/75">Descripción</label><textarea id="description" name="description" rows="4" maxlength="5000" class="w-full rounded-sm border border-white/15 bg-black/25 px-3 py-3 text-white">{{ old('description', $settings->description) }}</textarea>@error('description')<p class="mt-1 text-sm text-rose-300">{{ $message }}</p>@enderror</div>
            <div><label for="footer_text" class="mb-2 block text-sm text-white/75">Texto del pie de página</label><textarea id="footer_text" name="footer_text" rows="3" maxlength="2000" class="w-full rounded-sm border border-white/15 bg-black/25 px-3 py-3 text-white">{{ old('footer_text', $settings->footer_text) }}</textarea>@error('footer_text')<p class="mt-1 text-sm text-rose-300">{{ $message }}</p>@enderror</div>
        </section>

        <section class="glass-panel space-y-5 rounded-md p-5 sm:p-7" aria-labelledby="presentation-title">
            <div><h2 id="presentation-title" class="font-display text-lg font-semibold text-white">Presentación</h2><p class="mt-1 text-sm text-white/45">Idioma HTML público y zona horaria usada para mostrar fechas editoriales.</p></div>
            <div class="grid gap-5 sm:grid-cols-2"><div><label for="locale" class="mb-2 block text-sm text-white/75">Idioma</label><select id="locale" name="locale" class="w-full rounded-sm border border-white/15 bg-[#111217] px-3 py-3 text-white"><option value="es" @selected(old('locale', $settings->locale) === 'es')>Español</option><option value="en" @selected(old('locale', $settings->locale) === 'en')>English</option></select>@error('locale')<p class="mt-1 text-sm text-rose-300">{{ $message }}</p>@enderror</div><div><label for="presentation_timezone" class="mb-2 block text-sm text-white/75">Zona horaria de presentación</label><select id="presentation_timezone" name="presentation_timezone" class="w-full rounded-sm border border-white/15 bg-[#111217] px-3 py-3 text-white">@foreach(timezone_identifiers_list() as $timezone)<option value="{{ $timezone }}" @selected(old('presentation_timezone', $settings->presentation_timezone) === $timezone)>{{ $timezone }}</option>@endforeach</select>@error('presentation_timezone')<p class="mt-1 text-sm text-rose-300">{{ $message }}</p>@enderror</div></div>
        </section>

        <section class="glass-panel rounded-md p-5 sm:p-7" aria-labelledby="social-title"><div class="flex flex-wrap items-center justify-between gap-4"><div><h2 id="social-title" class="font-display text-lg font-semibold text-white">Redes sociales</h2><p class="mt-1 text-sm text-white/45">Las redes se conservan en el módulo existente y se muestran desde esa configuración.</p></div><a href="{{ route('admin.social-links.index') }}" class="rounded-sm border border-cyan/30 px-4 py-2.5 text-sm text-cyan">Administrar redes</a></div>@if($socialLinks->isNotEmpty())<ul class="mt-4 flex flex-wrap gap-2">@foreach($socialLinks as $socialLink)<li class="rounded-sm border border-white/10 px-3 py-2 text-xs text-white/65">{{ $socialLink->network_label }} · {{ $socialLink->is_active ? 'Activa' : 'Inactiva' }}</li>@endforeach</ul>@else<p class="mt-4 text-sm text-white/40">Todavía no hay redes configuradas.</p>@endif</section>

        <div class="flex flex-wrap gap-3"><button class="rounded-sm bg-cyan px-5 py-3 font-mono text-xs font-semibold tracking-wider text-void">GUARDAR CONFIGURACIÓN</button><a href="{{ route('admin.dashboard') }}" class="rounded-sm border border-white/15 px-5 py-3 text-sm text-white/70">Cancelar</a></div>
    </form>
</div>
@endsection
