@extends('layouts.admin')

@section('title', 'Configuración de correo')
@section('breadcrumb', 'CONFIGURACIÓN / CORREO')

@section('content')
<div class="mx-auto max-w-5xl space-y-6">
    <div><a href="{{ route('admin.settings.edit') }}" class="text-sm text-cyan hover:underline">← Configuración general</a><p class="mono-label mt-4 text-cyan">// TRANSPORTE DE CORREO</p><h1 class="mt-2 font-display text-3xl font-semibold text-white">Configuración de correo</h1><p class="mt-2 max-w-3xl text-sm leading-6 text-white/55">Configura el envío SMTP del CMS. Si esta configuración está inactiva, Laravel conserva su configuración de infraestructura como alternativa.</p></div>
    @if (session('status'))<div role="status" class="rounded-sm border border-emerald-400/20 bg-emerald-400/5 p-4 text-sm text-emerald-200">{{ session('status') }}</div>@endif
    @if (session('error'))<div role="alert" class="rounded-sm border border-rose-400/20 bg-rose-400/5 p-4 text-sm text-rose-200">{{ session('error') }}</div>@endif
    @if ($errors->any())<div role="alert" class="rounded-sm border border-rose-400/20 bg-rose-400/5 p-4 text-sm text-rose-200"><p class="font-medium">Revisa los campos indicados.</p><ul class="mt-2 list-inside list-disc">@foreach ($errors->all() as $error)<li>{{ $error }}</li>@endforeach</ul></div>@endif

    <form method="POST" action="{{ route('admin.settings.mail.update') }}" class="glass-panel space-y-6 rounded-md p-5 sm:p-7">
        @csrf @method('PUT')
        <section class="space-y-5" aria-labelledby="smtp-title">
            <div class="flex flex-wrap items-center justify-between gap-3"><div><h2 id="smtp-title" class="font-display text-lg font-semibold text-white">Servidor SMTP</h2><p class="mt-1 text-sm text-white/45">Los valores se aplican al sistema de correo central del CMS.</p></div><span class="rounded-sm border px-3 py-1.5 text-xs {{ $setting->is_active ? 'border-emerald-400/25 bg-emerald-400/5 text-emerald-200' : 'border-white/15 bg-white/5 text-white/55' }}">{{ $setting->is_active ? 'Configuración activa' : 'Usando alternativa de infraestructura' }}</span></div>
            <div><label for="mailer" class="mb-2 block text-sm text-white/75">Transportador</label><select id="mailer" name="mailer" class="w-full rounded-sm border border-white/15 bg-[#111217] px-3 py-3 text-white"><option value="smtp" selected>SMTP</option></select>@error('mailer')<p class="mt-1 text-sm text-rose-300">{{ $message }}</p>@enderror</div>
            <div class="grid gap-5 sm:grid-cols-2"><div><label for="host" class="mb-2 block text-sm text-white/75">Servidor SMTP</label><input id="host" name="host" autocomplete="off" maxlength="253" value="{{ old('host', $setting->host) }}" class="w-full rounded-sm border border-white/15 bg-black/25 px-3 py-3 text-white">@error('host')<p class="mt-1 text-sm text-rose-300">{{ $message }}</p>@enderror</div><div><label for="port" class="mb-2 block text-sm text-white/75">Puerto</label><input id="port" name="port" type="number" min="1" max="65535" value="{{ old('port', $setting->port) }}" class="w-full rounded-sm border border-white/15 bg-black/25 px-3 py-3 text-white">@error('port')<p class="mt-1 text-sm text-rose-300">{{ $message }}</p>@enderror</div></div>
            <div class="grid gap-5 sm:grid-cols-2"><div><label for="encryption" class="mb-2 block text-sm text-white/75">Cifrado</label><select id="encryption" name="encryption" class="w-full rounded-sm border border-white/15 bg-[#111217] px-3 py-3 text-white"><option value="" @selected(old('encryption', $setting->encryption) === null)>Sin especificar</option><option value="tls" @selected(old('encryption', $setting->encryption) === 'tls')>TLS / STARTTLS</option><option value="ssl" @selected(old('encryption', $setting->encryption) === 'ssl')>SSL</option></select>@error('encryption')<p class="mt-1 text-sm text-rose-300">{{ $message }}</p>@enderror</div><div><label for="username" class="mb-2 block text-sm text-white/75">Usuario SMTP (opcional)</label><input id="username" name="username" autocomplete="off" maxlength="254" value="{{ old('username', $setting->username) }}" class="w-full rounded-sm border border-white/15 bg-black/25 px-3 py-3 text-white">@error('username')<p class="mt-1 text-sm text-rose-300">{{ $message }}</p>@enderror</div></div>
            <div><label for="password" class="mb-2 block text-sm text-white/75">Contraseña SMTP</label><input id="password" name="password" type="password" value="" autocomplete="new-password" placeholder="{{ $hasPassword ? '••••••••••••' : 'Deja vacío si no se requiere' }}" class="w-full rounded-sm border border-white/15 bg-black/25 px-3 py-3 text-white"><p class="mt-1 text-xs text-white/45">{{ $hasPassword ? 'Hay una contraseña cifrada guardada. Si dejas este campo vacío, se conserva.' : 'Se almacenará cifrada con Laravel Crypt; nunca se volverá a mostrar.' }}</p>@error('password')<p class="mt-1 text-sm text-rose-300">{{ $message }}</p>@enderror</div>
        </section>

        <section class="space-y-5 border-t border-white/10 pt-6" aria-labelledby="sender-title">
            <div><h2 id="sender-title" class="font-display text-lg font-semibold text-white">Remitente</h2><p class="mt-1 text-sm text-white/45">La dirección y el nombre se usarán en los mensajes enviados por el CMS.</p></div>
            <div class="grid gap-5 sm:grid-cols-2"><div><label for="from_address" class="mb-2 block text-sm text-white/75">Correo remitente</label><input id="from_address" name="from_address" type="email" maxlength="254" value="{{ old('from_address', $setting->from_address) }}" class="w-full rounded-sm border border-white/15 bg-black/25 px-3 py-3 text-white">@error('from_address')<p class="mt-1 text-sm text-rose-300">{{ $message }}</p>@enderror</div><div><label for="from_name" class="mb-2 block text-sm text-white/75">Nombre remitente</label><input id="from_name" name="from_name" maxlength="180" value="{{ old('from_name', $setting->from_name) }}" class="w-full rounded-sm border border-white/15 bg-black/25 px-3 py-3 text-white">@error('from_name')<p class="mt-1 text-sm text-rose-300">{{ $message }}</p>@enderror</div></div>
            <input type="hidden" name="is_active" value="0"><label class="flex items-center gap-3 text-sm text-white/75"><input type="checkbox" name="is_active" value="1" @checked((bool) old('is_active', $setting->is_active)) class="accent-cyan">Activar SMTP guardado</label>@error('is_active')<p class="text-sm text-rose-300">{{ $message }}</p>@enderror
        </section>

        <div class="border-t border-white/10 pt-5"><button class="rounded-sm bg-cyan px-5 py-3 font-mono text-xs font-semibold tracking-wider text-void">GUARDAR CONFIGURACIÓN</button></div>
    </form>

    <section class="glass-panel rounded-md p-5 sm:p-7" aria-labelledby="test-mail-title"><h2 id="test-mail-title" class="font-display text-lg font-semibold text-white">Enviar correo de prueba</h2><p class="mt-1 text-sm text-white/45">Prueba la configuración guardada aunque aún esté inactiva. El mensaje no contiene credenciales ni datos técnicos; el resultado mostrará solo un aviso seguro.</p><form method="POST" action="{{ route('admin.settings.mail.test') }}" class="mt-5 flex flex-col gap-3 sm:flex-row">@csrf<label for="test_recipient" class="sr-only">Correo destinatario</label><input id="test_recipient" name="test_recipient" type="email" required maxlength="254" value="{{ old('test_recipient') }}" placeholder="destinatario@example.com" class="min-w-0 flex-1 rounded-sm border border-white/15 bg-black/25 px-3 py-3 text-white">@error('test_recipient')<span class="text-sm text-rose-300">{{ $message }}</span>@enderror<button class="rounded-sm border border-cyan/40 px-5 py-3 font-mono text-xs font-semibold tracking-wider text-cyan hover:bg-cyan/10">ENVIAR CORREO DE PRUEBA</button></form></section>
</div>
@endsection
