<div class="mx-auto max-w-3xl space-y-6">
    <div><a href="{{ route('admin.users.index') }}" class="text-sm text-cyan hover:underline">← Usuarios</a><h1 class="mt-3 font-display text-3xl font-semibold text-white">{{ $editing ? 'Editar usuario' : 'Crear usuario' }}</h1></div>
    @if ($errors->any())<div role="alert" class="rounded-sm border border-rose-400/20 bg-rose-400/5 p-4 text-sm text-rose-200"><p class="font-medium">Revisa los datos del formulario.</p><ul class="mt-2 list-inside list-disc">@foreach ($errors->all() as $error)<li>{{ $error }}</li>@endforeach</ul></div>@endif
    <form method="POST" action="{{ $editing ? route('admin.users.update', $managedUser) : route('admin.users.store') }}" class="glass-panel space-y-5 rounded-md p-5 sm:p-7">@csrf @if($editing) @method('PUT') @endif
        <div><label for="name" class="mb-2 block text-sm text-white/75">Nombre</label><input id="name" name="name" required maxlength="255" value="{{ old('name', $managedUser->name) }}" autocomplete="name" class="w-full rounded-sm border border-white/15 bg-black/25 px-3 py-3 text-white focus:border-cyan focus:outline-none">@error('name')<p class="mt-1 text-sm text-rose-300">{{ $message }}</p>@enderror</div>
        <div><label for="email" class="mb-2 block text-sm text-white/75">Correo</label><input id="email" name="email" type="email" required maxlength="255" value="{{ old('email', $managedUser->email) }}" autocomplete="email" class="w-full rounded-sm border border-white/15 bg-black/25 px-3 py-3 text-white focus:border-cyan focus:outline-none">@error('email')<p class="mt-1 text-sm text-rose-300">{{ $message }}</p>@enderror</div>
        <div><label for="password" class="mb-2 block text-sm text-white/75">{{ $editing ? 'Nueva contraseña (opcional)' : 'Contraseña' }}</label><input id="password" name="password" type="password" @required(!$editing) minlength="12" autocomplete="new-password" class="w-full rounded-sm border border-white/15 bg-black/25 px-3 py-3 text-white focus:border-cyan focus:outline-none"><p class="mt-1 text-xs text-white/40">Mínimo 12 caracteres, con letras y números. La contraseña actual nunca se muestra.</p>@error('password')<p class="mt-1 text-sm text-rose-300">{{ $message }}</p>@enderror</div>
        <div><label for="password_confirmation" class="mb-2 block text-sm text-white/75">{{ $editing ? 'Confirmar nueva contraseña' : 'Confirmar contraseña' }}</label><input id="password_confirmation" name="password_confirmation" type="password" @required(!$editing) minlength="12" autocomplete="new-password" class="w-full rounded-sm border border-white/15 bg-black/25 px-3 py-3 text-white focus:border-cyan focus:outline-none"></div>
        <div class="grid gap-5 sm:grid-cols-2"><div><label for="role" class="mb-2 block text-sm text-white/75">Rol</label><select id="role" name="role" required class="w-full rounded-sm border border-white/15 bg-[#111217] px-3 py-3 text-white"><option value="admin" @selected(old('role', $managedUser->role ?: 'admin') === 'admin')>Administrador</option><option value="editor" @selected(old('role', $managedUser->role) === 'editor')>Editor</option><option value="author" @selected(old('role', $managedUser->role) === 'author')>Autor</option>@if(auth()->user()->isSuperAdmin())<option value="super_admin" @selected(old('role', $managedUser->role) === 'super_admin')>Super Admin</option>@endif</select>@error('role')<p class="mt-1 text-sm text-rose-300">{{ $message }}</p>@enderror</div>
        <div><label for="status" class="mb-2 block text-sm text-white/75">Estado</label><select id="status" name="status" required class="w-full rounded-sm border border-white/15 bg-[#111217] px-3 py-3 text-white"><option value="active" @selected(old('status', $managedUser->status ?: 'active') === 'active')>Activo</option><option value="suspended" @selected(old('status', $managedUser->status) === 'suspended')>Suspendido</option><option value="blocked" @selected(old('status', $managedUser->status) === 'blocked')>Bloqueado</option></select>@error('status')<p class="mt-1 text-sm text-rose-300">{{ $message }}</p>@enderror</div></div>
        <div class="flex flex-wrap gap-3 border-t border-white/10 pt-5"><button class="rounded-sm bg-cyan px-5 py-3 font-mono text-xs font-semibold tracking-wider text-void">{{ $editing ? 'GUARDAR CAMBIOS' : 'CREAR USUARIO' }}</button><a href="{{ route('admin.users.index') }}" class="rounded-sm border border-white/15 px-5 py-3 text-sm text-white/70">Cancelar</a></div>
    </form>
</div>
