@php($editing = $post->exists)

<form method="POST" action="{{ $editing ? route('admin.posts.update', $post) : route('admin.posts.store') }}" enctype="multipart/form-data" class="mt-7 space-y-6">
    @csrf
    @if ($editing) @method('PUT') @endif
    @if ($errors->any())<div role="alert" class="rounded-sm border border-red-400/30 bg-red-400/10 p-4 text-sm text-red-200"><p class="font-medium">Revisa los campos marcados:</p><ul class="mt-2 list-inside list-disc space-y-1">@foreach ($errors->all() as $error)<li>{{ $error }}</li>@endforeach</ul></div>@endif
    <div class="grid gap-5 sm:grid-cols-2">
        <div><label for="title" class="mono-label mb-2 block text-white/65">Título *</label><input id="title" name="title" value="{{ old('title', $post->title) }}" required maxlength="200" class="w-full rounded-sm border border-white/10 bg-black/35 px-4 py-3 text-sm text-white outline-none focus:border-cyan focus:ring-2 focus:ring-cyan/15">@error('title')<p class="mt-2 text-sm text-red-300">{{ $message }}</p>@enderror</div>
        <div><label for="slug" class="mono-label mb-2 block text-white/65">Slug <span class="text-white/35">(opcional, editable)</span></label><input id="slug" name="slug" value="{{ old('slug', $post->slug) }}" maxlength="180" pattern="[A-Za-z0-9_-]+" placeholder="se-genera-desde-el-titulo" class="w-full rounded-sm border border-white/10 bg-black/35 px-4 py-3 font-mono text-sm text-white outline-none focus:border-cyan focus:ring-2 focus:ring-cyan/15">@error('slug')<p class="mt-2 text-sm text-red-300">{{ $message }}</p>@enderror</div>
        <div><label for="category_id" class="mono-label mb-2 block text-white/65">Categoría *</label><select id="category_id" name="category_id" required class="w-full rounded-sm border border-white/10 bg-black/35 px-4 py-3 text-sm text-white outline-none focus:border-cyan focus:ring-2 focus:ring-cyan/15"><option value="">Selecciona una categoría</option>@foreach ($categories as $category)<option value="{{ $category->id }}" @selected((string) old('category_id', $post->category_id) === (string) $category->id)>{{ $category->name }}{{ $category->is_active ? '' : ' (inactiva)' }}</option>@endforeach</select>@error('category_id')<p class="mt-2 text-sm text-red-300">{{ $message }}</p>@enderror</div>
        <div><label for="status" class="mono-label mb-2 block text-white/65">Estado *</label><select id="status" name="status" required class="w-full rounded-sm border border-white/10 bg-black/35 px-4 py-3 text-sm text-white outline-none focus:border-cyan focus:ring-2 focus:ring-cyan/15"><option value="draft" @selected(old('status', $post->status ?? 'draft') === 'draft')>Borrador</option><option value="published" @selected(old('status', $post->status) === 'published')>Publicada</option><option value="scheduled" @selected(old('status', $post->status) === 'scheduled')>Programada</option><option value="archived" @selected(old('status', $post->status) === 'archived')>Archivada</option></select>@error('status')<p class="mt-2 text-sm text-red-300">{{ $message }}</p>@enderror</div>
        <div class="sm:col-span-2"><label for="excerpt" class="mono-label mb-2 block text-white/65">Resumen</label><textarea id="excerpt" name="excerpt" maxlength="500" rows="3" class="w-full rounded-sm border border-white/10 bg-black/35 px-4 py-3 text-sm leading-6 text-white outline-none focus:border-cyan focus:ring-2 focus:ring-cyan/15">{{ old('excerpt', $post->excerpt) }}</textarea>@error('excerpt')<p class="mt-2 text-sm text-red-300">{{ $message }}</p>@enderror</div>
        <div class="sm:col-span-2"><label for="content" class="mono-label mb-2 block text-white/65">Contenido * <span class="text-white/35">(texto plano; HTML no permitido)</span></label><textarea id="content" name="content" required maxlength="50000" rows="12" class="w-full rounded-sm border border-white/10 bg-black/35 px-4 py-3 text-sm leading-7 text-white outline-none focus:border-cyan focus:ring-2 focus:ring-cyan/15">{{ old('content', $post->content) }}</textarea>@error('content')<p class="mt-2 text-sm text-red-300">{{ $message }}</p>@enderror</div>
        <div><label for="featured_image" class="mono-label mb-2 block text-white/65">Imagen destacada</label><input id="featured_image" name="featured_image" type="file" accept="image/jpeg,image/png,image/webp" class="block w-full rounded-sm border border-white/10 bg-black/35 p-3 text-sm text-white file:mr-4 file:rounded-sm file:border-0 file:bg-cyan file:px-3 file:py-2 file:font-mono file:text-xs file:font-semibold file:text-void" aria-describedby="image-help"> <p id="image-help" class="mt-2 text-xs text-white/45">JPG, PNG o WebP; máximo 5 MB y 6000 × 6000 px.</p>@error('featured_image')<p class="mt-2 text-sm text-red-300">{{ $message }}</p>@enderror @if ($editing && $post->featured_image)<img src="{{ \Illuminate\Support\Facades\Storage::disk('public')->url($post->featured_image) }}" alt="{{ $post->title }}" class="mt-3 h-24 w-36 rounded-sm border border-white/10 object-cover">@endif</div>
        <div><label for="published_at" class="mono-label mb-2 block text-white/65">Fecha de publicación</label><input id="published_at" name="published_at" type="datetime-local" value="{{ old('published_at', $post->published_at?->format('Y-m-d\TH:i')) }}" class="w-full rounded-sm border border-white/10 bg-black/35 px-4 py-3 text-sm text-white outline-none focus:border-cyan focus:ring-2 focus:ring-cyan/15" aria-describedby="published-help"> <p id="published-help" class="mt-2 text-xs text-white/45">Si eliges Programada, debe ser una fecha futura. Si eliges Publicada con fecha futura, se programará automáticamente.</p>@error('published_at')<p class="mt-2 text-sm text-red-300">{{ $message }}</p>@enderror</div>
        <div><label for="seo_title" class="mono-label mb-2 block text-white/65">Título SEO</label><input id="seo_title" name="seo_title" value="{{ old('seo_title', $post->seo_title) }}" maxlength="180" class="w-full rounded-sm border border-white/10 bg-black/35 px-4 py-3 text-sm text-white outline-none focus:border-cyan focus:ring-2 focus:ring-cyan/15">@error('seo_title')<p class="mt-2 text-sm text-red-300">{{ $message }}</p>@enderror</div>
        <div><label for="meta_description" class="mono-label mb-2 block text-white/65">Meta descripción</label><input id="meta_description" name="meta_description" value="{{ old('meta_description', $post->meta_description) }}" maxlength="300" class="w-full rounded-sm border border-white/10 bg-black/35 px-4 py-3 text-sm text-white outline-none focus:border-cyan focus:ring-2 focus:ring-cyan/15">@error('meta_description')<p class="mt-2 text-sm text-red-300">{{ $message }}</p>@enderror</div>
    </div>
    <div class="flex flex-wrap gap-3 border-t border-white/10 pt-5"><button type="submit" class="focus-cyan rounded-sm bg-cyan px-5 py-3 font-mono text-xs font-semibold tracking-wider text-void transition hover:brightness-110">{{ $editing ? 'GUARDAR CAMBIOS' : 'GUARDAR PUBLICACIÓN' }}</button><a href="{{ route('admin.posts.index') }}" class="focus-cyan rounded-sm border border-white/15 px-5 py-3 font-mono text-xs tracking-wider text-white/70 hover:border-white/30">CANCELAR</a></div>
</form>
