@php($editing = $category->exists)

<form method="POST" action="{{ $editing ? route('admin.categories.update', $category) : route('admin.categories.store') }}" class="mt-7 space-y-6">
    @csrf
    @if ($editing) @method('PUT') @endif
    @if ($errors->any())<div role="alert" class="rounded-sm border border-red-400/30 bg-red-400/10 p-4 text-sm text-red-200"><p class="font-medium">Revisa los campos marcados:</p><ul class="mt-2 list-inside list-disc space-y-1">@foreach ($errors->all() as $error)<li>{{ $error }}</li>@endforeach</ul></div>@endif
    <div class="grid gap-5 sm:grid-cols-2">
        <div><label for="name" class="mono-label mb-2 block text-white/65">Nombre *</label><input id="name" name="name" value="{{ old('name', $category->name) }}" required maxlength="160" class="w-full rounded-sm border border-white/10 bg-black/35 px-4 py-3 text-sm text-white outline-none focus:border-cyan focus:ring-2 focus:ring-cyan/15" aria-describedby="name-error">@error('name')<p id="name-error" class="mt-2 text-sm text-red-300">{{ $message }}</p>@enderror</div>
        <div><label for="slug" class="mono-label mb-2 block text-white/65">Slug *</label><input id="slug" name="slug" value="{{ old('slug', $category->slug) }}" required maxlength="180" pattern="[A-Za-z0-9_-]+" class="w-full rounded-sm border border-white/10 bg-black/35 px-4 py-3 font-mono text-sm text-white outline-none focus:border-cyan focus:ring-2 focus:ring-cyan/15" aria-describedby="slug-help slug-error"><p id="slug-help" class="mt-2 text-xs text-white/45">Único; solo letras, números, guiones y guiones bajos.</p>@error('slug')<p id="slug-error" class="mt-2 text-sm text-red-300">{{ $message }}</p>@enderror</div>
        <div class="sm:col-span-2"><label for="description" class="mono-label mb-2 block text-white/65">Descripción</label><textarea id="description" name="description" maxlength="5000" rows="5" class="w-full rounded-sm border border-white/10 bg-black/35 px-4 py-3 text-sm leading-6 text-white outline-none focus:border-cyan focus:ring-2 focus:ring-cyan/15">{{ old('description', $category->description) }}</textarea>@error('description')<p class="mt-2 text-sm text-red-300">{{ $message }}</p>@enderror</div>
        <div class="flex items-center gap-3"><input type="hidden" name="is_active" value="0"><input id="is_active" name="is_active" type="checkbox" value="1" @checked((bool) old('is_active', $category->is_active ?? false)) class="h-4 w-4 accent-cyan"><label for="is_active" class="text-sm text-white/75">Categoría activa</label></div>
    </div>
    <div class="flex flex-wrap gap-3 border-t border-white/10 pt-5"><button type="submit" class="focus-cyan rounded-sm bg-cyan px-5 py-3 font-mono text-xs font-semibold tracking-wider text-void transition hover:brightness-110">{{ $editing ? 'GUARDAR CAMBIOS' : 'CREAR CATEGORÍA' }}</button><a href="{{ route('admin.categories.index') }}" class="focus-cyan rounded-sm border border-white/15 px-5 py-3 font-mono text-xs tracking-wider text-white/70 hover:border-white/30">CANCELAR</a></div>
</form>
